### ISSUE TITLE
Bin In Sequence

### ISSUE THREAD

**Issue by bfkelsey** [thomasnield/kotlin-statistics#12]
It would be nice to be able to bin items in groups based on a certain order. So the user could pass in a sort and then it could bin every n items. 

For example: 
I have 1, 2, 3, 4, 5 and I want it binned by 2 in order it could return 
bin 1 - 1,2
bin 2 - 3,4
bin3 - 5

**Comment by bfkelsey** [comment]
I would also like to run more then one function on the binned items. Like have the ability to pass in multiple functions and have the results for each bin returned. Then also have the list of items in the bin returned.

**Comment by thomasnield** [comment]
Sorry for delay in response. Interesting idea, let me process this. But how will the bucketed objects be put in the buckets? 

I'm releasing 1.0 right now. Maybe we can discuss and consider this feature for the next release.

**Comment by thomasnield** [comment]
Do you think this overlaps with the `windowed()` function introduced in Kotlin 1.2? https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/windowed.html

**Comment by bfkelsey** [comment]
Yeah I think windowed function does solve this use case.
