### ISSUE TITLE
Simple example of averageBy does not compile in Intellij IDEA

### ISSUE THREAD

**Issue by EpineiroBumeran** [thomasnield/kotlin-statistics#13]
Hi,

I trying to run a simple example of your library taken from here http://tomstechnicalblog.blogspot.com.ar/2017/05/introducing-kotlin-statistics.html. The example is only a Main.kt with the following code:

```kotlin
package com.example

import org.nield.kotlinstatistics.averageBy
import java.time.LocalDate

data class Patient(val firstName: String,
                   val lastName: String,
                   val gender: Gender,
                   val birthday: LocalDate,
                   val whiteBloodCellCount: Int)


val patients = listOf(
        Patient("John", "Simone", Gender.MALE, LocalDate.of(1989, 1, 7), 4500),
        Patient("Sarah", "Marley", Gender.FEMALE, LocalDate.of(1970, 2, 5), 6700),
        Patient("Jessica", "Arnold", Gender.FEMALE, LocalDate.of(1980, 3, 9), 3400),
        Patient("Sam", "Beasley", Gender.MALE, LocalDate.of(1981, 4, 17), 8800),
        Patient("Dan", "Forney", Gender.MALE, LocalDate.of(1985, 9, 13), 5400),
        Patient("Lauren", "Michaels", Gender.FEMALE, LocalDate.of(1975, 8, 21), 5000),
        Patient("Michael", "Erlich", Gender.MALE, LocalDate.of(1985, 12, 17), 4100),
        Patient("Jason", "Miles", Gender.MALE, LocalDate.of(1991, 11, 1), 3900),
        Patient("Rebekah", "Earley", Gender.FEMALE, LocalDate.of(1985, 2, 18), 4600),
        Patient("James", "Larson", Gender.MALE, LocalDate.of(1974, 4, 10), 5100),
        Patient("Dan", "Ulrech", Gender.MALE, LocalDate.of(1991, 7, 11), 6000),
        Patient("Heather", "Eisner", Gender.FEMALE, LocalDate.of(1994, 3, 6), 6000),
        Patient("Jasper", "Martin", Gender.MALE, LocalDate.of(1971, 7, 1), 6000)
)

enum class Gender {
    MALE,
    FEMALE
}

fun main(args: Array<String>) {

    val averageWbccByGender = patients.averageBy(
            keySelector = {  it.gender },
            intMapper = { it.whiteBloodCellCount }
    )

    println(averageWbccByGender)
}
```

Both "it" in the lambdas of averageBy are unresolved and Intellij cannot find the correct averageBy to call with those arguments. The complete error is as follows:

`None of the following functions can be called with the arguments supplied.
Iterable<Patient>.averageBy((Patient) → K, (Patient) → BigDecimal)   where K cannot be inferred; T = Patient for    inline fun <T, K> Iterable<T>.averageBy(crossinline keySelector: (T) → K, crossinline bigDecimalSelector: (T) → BigDecimal): Map<K, BigDecimal> defined in org.nield.kotlinstatistics
Iterable<Patient>.averageBy((Patient) → K, (Patient) → Double)   where K cannot be inferred; T = Patient for    inline fun <T, K> Iterable<T>.averageBy(crossinline keySelector: (T) → K, crossinline doubleSelector: (T) → Double): Map<K, Double> defined in org.nield.kotlinstatistics
Iterable<Patient>.averageBy((Patient) → K, (Patient) → Int)   where K cannot be inferred; T = Patient for    inline fun <T, K> Iterable<T>.averageBy(crossinline keySelector: (T) → K, crossinline intSelector: (T) → Int): Map<K, Double> defined in org.nield.kotlinstatistics
Iterable<Patient>.averageBy((Patient) → K, (Patient) → Long)   where K cannot be inferred; T = Patient for    inline fun <T, K> Iterable<T>.averageBy(crossinline keySelector: (T) → K, crossinline valueSelector: (T) → Long): Map<K, Double> defined in org.nield.kotlinstatistics
Iterable<Pair<K, BigDecimal>>.averageBy()   where K cannot be inferred for    fun <K> Iterable<Pair<K, BigDecimal>>.averageBy(): Map<K, BigDecimal> defined in org.nield.kotlinstatistics
Iterable<Pair<K, Double>>.averageBy()   where K cannot be inferred for    fun <K> Iterable<Pair<K, Double>>.averageBy(): Map<K, Double> defined in org.nield.kotlinstatistics
Iterable<Pair<K, Int>>.averageBy()   where K cannot be inferred for    fun <K> Iterable<Pair<K, Int>>.averageBy(): Map<K, Double> defined in org.nield.kotlinstatistics
Iterable<Pair<K, Long>>.averageBy()   where K cannot be inferred for    fun <K> Iterable<Pair<K, Long>>.averageBy(): Map<K, Double> defined in org.nield.kotlinstatistics`

Mi version of IDEA is 2017.2.5, I'm using JDK 1.8.0_121, Kotlin plugin version 1.1.51 and the following maven dependency in my project:

``` xml
       <dependency>
            <groupId>org.nield</groupId>
            <artifactId>kotlin-statistics</artifactId>
            <version>1.0.0</version>
        </dependency>
```

I think your library looks very promising, but currently I cannot even run a simple example. 
Thanks in advance for any comments that you may have!!

**Comment by thomasnield** [comment]
Hey sorry for delay in response. I'll take a look tomorrow.

**Comment by thomasnield** [comment]
Hey quick note (I'm on my phone), the examples from my blog are likely deprecated due to a major refactoring for the 1.0 release, where I simplified a lot of the API. That is likely why it isn't compiling.

Please use the README as a reference on how the API works now. Ill put together better documentation later.

**Comment by thomasnield** [comment]
Please reopen if you are still having an issue.

**Comment by hudsonb** [comment]
`sumBy` and `averageBy` are still ambiguous, and should probably be renamed or removed.
