### ISSUE TITLE
Gradle Build fails

### ISSUE THREAD

**Issue by dibog** [thomasnield/kotlin-statistics#28]
Hi Thomas,

I tried to use your project. Unfortunatly your artifact is available on maven central or similary.
It is theoretically available on JitPack. But Jitpack (same as me) can't build your project (I think
its the same reason)

JitPack build log: https://jitpack.io/com/github/thomasnield/kotlin-statistics/1.1.3/build.log) 

My failing tries are at the end of this posting.

If you would have a pom, I would be able to look at it. But I have not much clue about gradle,
as maven works fine for me.

Best regards,
Dieter

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\temp\kotlin-statistics-1.1.3\build.gradle' line: 61

* What went wrong:
A problem occurred evaluating root project 'kotlin-statistics-1.1.3'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.14 secs

**Comment by dibog** [comment]
@all : Please find here a minimal pom.xml to build the version 1.1.3. You can install or deploy it into your local maven repo.

@thomasnield : Here is a pom.xml which can be used publishing the jar on maven central: https://raw.githubusercontent.com/dibog/pom-to-dot/master/pom.xml

Best regards,
Dieter

**Comment by thomasnield** [comment]
I'm confused. Is it [not on Maven Central](https://search.maven.org/#artifactdetails%7Corg.nield%7Ckotlin-statistics%7C1.1.3%7Cjar)? Or are you trying to access it strictly through JitPack? 

And thanks! I'll add the POM. I've been having issues with JitPack and Gradle on mulitple projects so I may just switch to Maven.

**Comment by thomasnield** [comment]
Oh wait, your Gradle build is getting mad because it doesn't have the key files. I need to disable those parts of the `build.gradle` script before putting it up on the repo.

**Comment by thomasnield** [comment]
Oh wait, your Gradle build is getting mad because it doesn't have the key files. I need to disable those parts of the build.gradle script before putting it up on the repo.

Alright, try it now. It seems to be working correctly.

**Comment by dibog** [comment]
Hi Thomas,

I was confused with the following fragment from your documentation:

```
  <repositories>
      <repository>
          <id>jitpack.io</id>
          <url>https://jitpack.io</url>
      </repository>
  </repositories>
  <dependency>
      <groupId>com.github.thomasnield</groupId>
      <artifactId>kotlin-statistics</artifactId>
      <version>-SNAPSHOT</version>
  </dependency>

```
I searched for com.github.thomasnield and not for org.nield. Could you please update that on the https://github.com/thomasnield/kotlin-statistics/blob/master/README.md ?

Thanks,
Dieter

**Comment by thomasnield** [comment]
Dieter, I believe JItPack uses a GitHub domain as part of the convention: 
https://jitpack.io/#thomasnield/kotlin-statistics/-SNAPSHOT

**Comment by thomasnield** [comment]
This should be fixed now. Needed to comment out deployment parts of Gradle script
